### ISSUE TITLE
Removed from Chrome Store

### ISSUE THREAD

**Issue by Alber70g** [orschiro/tsrlt-chrome-extension#11]
The extension seems to be removed from the Chrome Webstore: https://chrome.google.com/webstore/detail/toggle-switch-recent-last/odhjcgnlbagjllfbilicalpigimhdcll?hl=te

Hope you can fix it?

**Comment by orschiro** [comment]
Can you please try this extension?

https://chrome.google.com/webstore/detail/clut-cycle-last-used-tabs/cobieddmkhhnbeldhncnfcgcaccmehgn

**Comment by pashkasan** [comment]
you can install from download, Menu->Additional Tools->Extensions->  developer mode -> load extension from disk

**Comment by CicoZhang** [comment]
Could you please restore the link in Chrome store?

**Comment by orschiro** [comment]
@CicoZhang restored. :-)
