### ISSUE TITLE
Not working with chrome 57.0.2987.98 (64-bit)

### ISSUE THREAD

**Issue by menocomp** [orschiro/tsrlt-chrome-extension#13]
The extension stopped working for no reason!
I am running Ubuntu and chrome Version 57.0.2987.98 (64-bit) and extension version 1.6.4. 
I am running the free version of the extension.

**Comment by orschiro** [comment]
Can you please upgrade your Chrome to `Version 57.0.2987.133 (64-bit)`?

This is the version I use on Ubuntu 17.04 and it works without problems.

**Comment by orschiro** [comment]
Not a bug.
