### ISSUE TITLE
keyboard shortcut for toggle extension options

### ISSUE THREAD

**Issue by control-freak** [orschiro/tsrlt-chrome-extension#9]
is it possible to toggle between go to last tab on close and chrome default option? i have this gestures for my pc so is it possible to setup two gestures, one to close like default chrome and one to close to the last tab? i dont no anything about coding so sorry if i sound stupid

**Comment by orschiro** [comment]
Dear @control-freak,

Thanks for your request!

> is it possible to toggle between go to last tab on close and chrome default option?

In what way would you want to toggle between these two? 

Have you checked the options page already?

![image](https://cloud.githubusercontent.com/assets/170947/14759898/7fdc666e-0933-11e6-99a8-bfa0ccbf64d7.png)

>  i have this gestures for my pc so is it possible to setup two gestures, one to close like default chrome and one to close to the last tab?

So you would want to have two distinct keyboard shortcuts?

~Robert

**Comment by control-freak** [comment]
yes i've checked the option. but i am facing a problem with my gesture software. i use strokesplus. and my lua code is like dis 

 acSendAltDown()
acSendKeys("Q")
acSendAltUp()

ive tried acSendKeys("%Q") too but gesture doesnt get me back to last tab. in lua %=alt. if u have any idea can u help me with this?

yes it'd be perfect for me if this extension has two keyboard shortcuts which toggles between default chrome behavior and close to last tab. that way i can just put two gestures that switchs between two keyboard shortcuts and close the way i want those to.

**Comment by orschiro** [comment]
- Why do you need to use your gesture software to trigger the shortcut?
- Does it work if you change the default shortcut `Alt+Q` to something else in `chrome:extensions`?

**Comment by control-freak** [comment]
i've found the shortcut in chrome:extensions.it is working with my gesture app. but if i press the shortcut key for activate this extension it takes me to the last tab. how does this option work? do i have to close chrome to make it work?

sometimes i want to close a chrome tab normally and sometimes i want to close one tab and go to the last tab i was working. so if i could somehow activate the extension when i want to go the last tab after closing then it'd be great for me. am sorry my english is not good. dont no if my explanation was clear enough.

**Comment by orschiro** [comment]
Dear @control-freak,

I am afraid I can't help myself on adding this (niche) feature. 

I don't think that many users actually use additional gesture apps and spending time on figuring out how to find a solution to this, is not worth the time. 

However, I will mark this as an enhancement and encourage others to pick this up!

Warmly,

~Robert

**Comment by control-freak** [comment]
hey
you dont have to do anything new. i didnt know that your extension already has the keyboard shortcut for things i wanted. but activating the extension keyboard shortcut doesnt activate or de activate the shortcut. it switches tab to the last one or something like that. can u tell me how does it work?
![image](https://cloud.githubusercontent.com/assets/18626442/14940616/2ebeee2e-0f9f-11e6-8a05-fabe3fda79e6.png)

**Comment by orschiro** [comment]
Hi @control-freak,

I'm not even sure if "Activate the extension" actually does provide a function. 

"Toggle tabs", however, should work.

~Robett

**Comment by control-freak** [comment]
thank you anyways. love ur extension. keep up the good work.

**Comment by orschiro** [comment]
That's very nice to hear. I appreciate your kind words!

And bear in mind that there were others who helped this extension to become what it is. :-)

~Robert
